// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: modelopr.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

// Enum value maps for UploadStatusCode.
var (
	UploadStatusCode_name = map[int32]string{
		0: "Unknown",
		1: "Ok",
		2: "Failed",
	}
	UploadStatusCode_value = map[string]int32{
		"Unknown": 0,
		"Ok":      1,
		"Failed":  2,
	}
)

func (x UploadStatusCode) Enum() *UploadStatusCode {
	p := new(UploadStatusCode)
	*p = x
	return p
}

func (x UploadStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_modelopr_proto_enumTypes[0].Descriptor()
}

func (UploadStatusCode) Type() protoreflect.EnumType {
	return &file_modelopr_proto_enumTypes[0]
}

func (x UploadStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadStatusCode.Descriptor instead.
func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{0}
}

type ModelInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ModelInfoReq) Reset() {
	*x = ModelInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelopr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoReq) ProtoMessage() {}

func (x *ModelInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modelopr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoReq.ProtoReflect.Descriptor instead.
func (*ModelInfoReq) Descriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{0}
}

func (x *ModelInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurVer     string `protobuf:"bytes,1,opt,name=CurVer,proto3" json:"CurVer,omitempty"`
	StagingVer string `protobuf:"bytes,2,opt,name=StagingVer,proto3" json:"StagingVer,omitempty"`
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelopr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_modelopr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{1}
}

func (x *ModelInfo) GetCurVer() string {
	if x != nil {
		return x.CurVer
	}
	return ""
}

func (x *ModelInfo) GetStagingVer() string {
	if x != nil {
		return x.StagingVer
	}
	return ""
}

type UploadModelObjReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Staging string `protobuf:"bytes,2,opt,name=Staging,proto3" json:"Staging,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *UploadModelObjReq) Reset() {
	*x = UploadModelObjReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelopr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadModelObjReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelObjReq) ProtoMessage() {}

func (x *UploadModelObjReq) ProtoReflect() protoreflect.Message {
	mi := &file_modelopr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelObjReq.ProtoReflect.Descriptor instead.
func (*UploadModelObjReq) Descriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{2}
}

func (x *UploadModelObjReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadModelObjReq) GetStaging() string {
	if x != nil {
		return x.Staging
	}
	return ""
}

func (x *UploadModelObjReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadModelObjResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version string           `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Code    UploadStatusCode `protobuf:"varint,3,opt,name=Code,proto3,enum=da.UploadStatusCode" json:"Code,omitempty"`
}

func (x *UploadModelObjResp) Reset() {
	*x = UploadModelObjResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelopr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadModelObjResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadModelObjResp) ProtoMessage() {}

func (x *UploadModelObjResp) ProtoReflect() protoreflect.Message {
	mi := &file_modelopr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadModelObjResp.ProtoReflect.Descriptor instead.
func (*UploadModelObjResp) Descriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{3}
}

func (x *UploadModelObjResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadModelObjResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadModelObjResp) GetCode() UploadStatusCode {
	if x != nil {
		return x.Code
	}
	return UploadStatusCode_Unknown
}

type ModelObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *ModelObj) Reset() {
	*x = ModelObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelopr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelObj) ProtoMessage() {}

func (x *ModelObj) ProtoReflect() protoreflect.Message {
	mi := &file_modelopr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelObj.ProtoReflect.Descriptor instead.
func (*ModelObj) Descriptor() ([]byte, []int) {
	return file_modelopr_proto_rawDescGZIP(), []int{4}
}

func (x *ModelObj) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_modelopr_proto protoreflect.FileDescriptor

var file_modelopr_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x64, 0x61, 0x22, 0x22, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x56, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x75, 0x72, 0x56, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x22, 0x5b, 0x0a,
	0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x12, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x64,
	0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x4f, 0x62, 0x6a, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2a, 0x33, 0x0a, 0x10, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x32,
	0xc5, 0x02, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x70, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x2e, 0x64, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x64, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x12, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x64,
	0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x42, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x64, 0x61, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x73, 0x61, 0x76, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x15, 0x2e, 0x64, 0x61, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x64, 0x61, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x32, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x2e, 0x64, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x61, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x4f, 0x62, 0x6a, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modelopr_proto_rawDescOnce sync.Once
	file_modelopr_proto_rawDescData = file_modelopr_proto_rawDesc
)

func file_modelopr_proto_rawDescGZIP() []byte {
	file_modelopr_proto_rawDescOnce.Do(func() {
		file_modelopr_proto_rawDescData = protoimpl.X.CompressGZIP(file_modelopr_proto_rawDescData)
	})
	return file_modelopr_proto_rawDescData
}

var file_modelopr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modelopr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modelopr_proto_goTypes = []interface{}{
	(UploadStatusCode)(0),      // 0: da.UploadStatusCode
	(*ModelInfoReq)(nil),       // 1: da.ModelInfoReq
	(*ModelInfo)(nil),          // 2: da.ModelInfo
	(*UploadModelObjReq)(nil),  // 3: da.UploadModelObjReq
	(*UploadModelObjResp)(nil), // 4: da.UploadModelObjResp
	(*ModelObj)(nil),           // 5: da.ModelObj
}
var file_modelopr_proto_depIdxs = []int32{
	0, // 0: da.UploadModelObjResp.Code:type_name -> da.UploadStatusCode
	1, // 1: da.ModelOprService.getModelInfo:input_type -> da.ModelInfoReq
	3, // 2: da.ModelOprService.saveStagingVersion:input_type -> da.UploadModelObjReq
	1, // 3: da.ModelOprService.commitStagingVersion:input_type -> da.ModelInfoReq
	3, // 4: da.ModelOprService.saveModel:input_type -> da.UploadModelObjReq
	1, // 5: da.ModelOprService.getLatestModel:input_type -> da.ModelInfoReq
	2, // 6: da.ModelOprService.getModelInfo:output_type -> da.ModelInfo
	4, // 7: da.ModelOprService.saveStagingVersion:output_type -> da.UploadModelObjResp
	4, // 8: da.ModelOprService.commitStagingVersion:output_type -> da.UploadModelObjResp
	4, // 9: da.ModelOprService.saveModel:output_type -> da.UploadModelObjResp
	5, // 10: da.ModelOprService.getLatestModel:output_type -> da.ModelObj
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modelopr_proto_init() }
func file_modelopr_proto_init() {
	if File_modelopr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modelopr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelopr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelopr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadModelObjReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelopr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadModelObjResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelopr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modelopr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modelopr_proto_goTypes,
		DependencyIndexes: file_modelopr_proto_depIdxs,
		EnumInfos:         file_modelopr_proto_enumTypes,
		MessageInfos:      file_modelopr_proto_msgTypes,
	}.Build()
	File_modelopr_proto = out.File
	file_modelopr_proto_rawDesc = nil
	file_modelopr_proto_goTypes = nil
	file_modelopr_proto_depIdxs = nil
}
